# Generated by Django 3.2.15 on 2022-12-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='type')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='tag')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='color')),
                ('status', models.TextField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=100, null=True)),
                ('ref', models.TextField(blank=True, max_length=10, null=True)),
                ('to', models.TextField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('due', models.DateField(auto_now=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.TextField(choices=[(1, 'Waiting For Payment'), (2, 'paid')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('cost_per_nit', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.TextField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='tag')),
                ('descr', models.TextField(blank=True, max_length=100, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, null=True)),
                ('transaction_date', models.DateField(auto_created=True)),
                ('payment_number', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('sales', 'sales'), ('purchases', 'purchases'), ('receipts', 'receipts'), ('payments', 'payments')], max_length=50, null=True)),
                ('ref', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Second Deposit'), (3, 'Third Deposit'), (4, 'Full Payment')], default='', null=True)),
                ('mode', models.IntegerField(choices=[(1, 'Cash'), (2, 'Check'), (3, 'Credit/Debit Card')], default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('currency', models.TextField(choices=[(1, 'Waiting For Payment'), (2, 'paid')], null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptwo.invoice')),
            ],
        ),
    ]
