# Generated by Django 3.2.15 on 2022-12-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro_serv',
            old_name='cost_per_nit',
            new_name='cost_per_unit',
        ),
    ]
