# Generated by Django 3.2.15 on 2022-12-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0002_rename_cost_per_nit_pro_serv_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_serv',
            name='low_stock',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pro_serv',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pro_serv',
            name='tag',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='tag'),
        ),
    ]
