# Generated by Django 3.2.15 on 2022-12-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0018_auto_20221214_1926'),
        ('apptwo', '0004_auto_20221214_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appone.patient'),
        ),
    ]
