# Generated by Django 3.2.15 on 2022-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0005_alter_invoice_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Check'), (3, 'Credit/Debit Card')], default='', max_length=12),
        ),
    ]
