# Generated by Django 3.2.15 on 2022-12-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0006_auto_20221214_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.IntegerField(null=True),
        ),
    ]
