# Generated by Django 3.2.15 on 2022-12-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0007_alter_payment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Check'), (3, 'Credit/Debit Card')], default=''),
        ),
    ]
