# Generated by Django 3.2.15 on 2022-12-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0008_alter_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting For Payment'), (2, 'paid')], null=True),
        ),
    ]
