# Generated by Django 3.2.15 on 2022-12-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appone.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(null=True, upload_to=None, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branche',
            name='email',
            field=models.EmailField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.TextField(choices=[('mr.', 'Mr.'), ('mrs.', 'Mrs.'), ('miss', 'Miss')], max_length=10, null=True),
        ),
    ]
