# Generated by Django 3.2.15 on 2022-12-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_alter_appointment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='appointment',
        ),
    ]
