# Generated by Django 3.2.15 on 2022-12-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_auto_20221214_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointment',
        ),
    ]
