# Generated by Django 3.2.15 on 2022-12-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_remove_doctor_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
    ]
