# Generated by Django 3.2.15 on 2022-12-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_remove_patient_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
    ]
