# Generated by Django 3.2.15 on 2022-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0010_remove_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allargies',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(choices=[('mr.', 'Mr.'), ('mrs.', 'Mrs.'), ('miss', 'Miss')], max_length=10, null=True),
        ),
    ]
