# Generated by Django 3.2.15 on 2022-12-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0012_auto_20221214_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(max_length=500, null=True)),
                ('note_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appone.doctor')),
                ('note_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appone.patient')),
            ],
        ),
    ]
