# Generated by Django 3.2.15 on 2022-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0013_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='appt',
            field=models.BooleanField(null=True),
        ),
    ]
