# Generated by Django 3.2.15 on 2022-12-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0014_queue_appt'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='image'),
        ),
    ]
