# Generated by Django 3.2.15 on 2022-12-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0015_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='wait_time',
            field=models.DurationField(editable=False, null=True),
        ),
    ]
