# Generated by Django 3.2.15 on 2022-12-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0016_auto_20221214_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='time_in',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='time_out',
            field=models.TimeField(auto_now=True),
        ),
    ]
