# Generated by Django 3.2.15 on 2022-12-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0017_auto_20221214_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.TextField(choices=[('done', 'Done'), ('waiting', 'Waiting'), ('process', 'Process'), ('cancel', 'Cancel')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='time_in',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='time_out',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
