# Generated by Django 3.2.15 on 2022-12-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0018_auto_20221214_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='ref_number',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
